// Code generated by ./cmd/gen; DO NOT EDIT.

package libwebp

var (
	xWebPGetInfo                   func(data *byte, dataSize uintptr, width *int32, height *int32) int32
	xWebPDecodeRGBA                func(data *byte, dataSize uintptr, width *int32, height *int32) *byte
	xWebPDecodeARGB                func(data *byte, dataSize uintptr, width *int32, height *int32) *byte
	xWebPDecodeBGRA                func(data *byte, dataSize uintptr, width *int32, height *int32) *byte
	xWebPDecodeRGB                 func(data *byte, dataSize uintptr, width *int32, height *int32) *byte
	xWebPDecodeBGR                 func(data *byte, dataSize uintptr, width *int32, height *int32) *byte
	xWebPDecodeRGBAInto            func(data *byte, dataSize uintptr, outputBuffer *byte, outputBufferSize uintptr, outputStride int32) *byte
	xWebPDecodeARGBInto            func(data *byte, dataSize uintptr, outputBuffer *byte, outputBufferSize uintptr, outputStride int32) *byte
	xWebPDecodeBGRAInto            func(data *byte, dataSize uintptr, outputBuffer *byte, outputBufferSize uintptr, outputStride int32) *byte
	xWebPDecodeRGBInto             func(data *byte, dataSize uintptr, outputBuffer *byte, outputBufferSize uintptr, outputStride int32) *byte
	xWebPDecodeBGRInto             func(data *byte, dataSize uintptr, outputBuffer *byte, outputBufferSize uintptr, outputStride int32) *byte
	xWebPDecodeYUV                 func(data *byte, dataSize uintptr, width *int32, height *int32, u **byte, v **byte, stride *int32, uvStride *int32) *byte
	xWebPDecodeYUVInto             func(data *byte, dataSize uintptr, luma *byte, lumaSize uintptr, lumaStride int32, u *byte, uSize uintptr, uStride int32, v *byte, vSize uintptr, vStride int32) *byte
	xWebPGetFeaturesInternal       func(data *byte, dataSize uintptr, features *WebPBitstreamFeatures, abiVersion int32) VP8StatusCode
	xWebPInitDecBufferInternal     func(buffer *WebPDecBuffer, abiVersion int32) int32
	xWebPFreeDecBuffer             func(buffer *WebPDecBuffer)
	xWebPInitDecoderConfigInternal func(config *WebPDecoderConfig, abiVersion int32) int32
	xWebPValidateDecoderConfig     func(config *WebPDecoderConfig) int32
	xWebPDecode                    func(data *byte, dataSize uintptr, config *WebPDecoderConfig) VP8StatusCode
	xWebPINewDecoder               func(outputBuffer *WebPDecBuffer) uintptr
	xWebPINewRGB                   func(csp int32, outputBuffer *byte, outputBufferSize uintptr, outputStride int32) uintptr
	xWebPINewYUVA                  func(luma *byte, lumaSize uintptr, lumaStride int32, u *byte, uSize uintptr, uStride int32, v *byte, vSize uintptr, vStride int32, a *byte, aSize uintptr, aStride int32) uintptr
	xWebPINewYUV                   func(luma *byte, lumaSize uintptr, lumaStride int32, u *byte, uSize uintptr, uStride int32, v *byte, vSize uintptr, vStride int32) uintptr
	xWebPIDelete                   func(idec uintptr)
	xWebPIAppend                   func(idec uintptr, data *byte, dataSize uintptr) VP8StatusCode
	xWebPIUpdate                   func(idec uintptr, data *byte, dataSize uintptr) VP8StatusCode
	xWebPIDecGetRGB                func(idec uintptr, lastY *int32, width *int32, height *int32, stride *int32) *byte
	xWebPIDecGetYUVA               func(idec uintptr, lastY *int32, u **byte, v **byte, a **byte, width *int32, height *int32, stride *int32, uvStride *int32, aStride *int32) *byte
	xWebPIDecodedArea              func(idec uintptr, left *int32, top *int32, width *int32, height *int32) *WebPDecBuffer
	xWebPIDecode                   func(data *byte, dataSize uintptr, config *WebPDecoderConfig) uintptr
	xWebPEncodeRGBA                func(rgba *byte, width int32, height int32, stride int32, quality float32, output **byte) uintptr
	xWebPEncodeRGB                 func(rgb *byte, width int32, height int32, stride int32, quality float32, output **byte) uintptr
	xWebPEncodeBGR                 func(bgr *byte, width int32, height int32, stride int32, quality float32, output **byte) uintptr
	xWebPEncodeBGRA                func(bgra *byte, width int32, height int32, stride int32, quality float32, output **byte) uintptr
	xWebPEncodeLosslessRGBA        func(rgba *byte, width int32, height int32, stride int32, output **byte) uintptr
	xWebPEncodeLosslessRGB         func(rgb *byte, width int32, height int32, stride int32, output **byte) uintptr
	xWebPEncodeLosslessBGR         func(bgr *byte, width int32, height int32, stride int32, output **byte) uintptr
	xWebPEncodeLosslessBGRA        func(bgra *byte, width int32, height int32, stride int32, output **byte) uintptr
	xWebPConfigInitInternal        func(config *WebPConfig, preset int32, quality float32, abiVersion int32) int32
	xWebPConfigLosslessPreset      func(config *WebPConfig, level int32) int32
	xWebPValidateConfig            func(config *WebPConfig) int32
	xWebPMemoryWriterInit          func(writer *WebPMemoryWriter)
	xWebPMemoryWriterClear         func(writer *WebPMemoryWriter)
	xWebPMemoryWrite               func(data *byte, dataSize uintptr, picture *WebPPicture) int32
	xWebPPictureInitInternal       func(picture *WebPPicture, abiVersion int32) int32
	xWebPPictureAlloc              func(picture *WebPPicture) int32
	xWebPPictureFree               func(picture *WebPPicture)
	xWebPPictureCopy               func(src *WebPPicture, dst *WebPPicture) int32
	xWebPPictureCrop               func(picture *WebPPicture, left int32, top int32, width int32, height int32) int32
	xWebPPictureView               func(src *WebPPicture, left int32, top int32, width int32, height int32, dst *WebPPicture) int32
	xWebPPictureIsView             func(picture *WebPPicture) int32
	xWebPPictureRescale            func(picture *WebPPicture, width int32, height int32) int32
	xWebPPictureImportRGB          func(picture *WebPPicture, rgb *byte, rgbStride int32) int32
	xWebPPictureImportRGBA         func(picture *WebPPicture, rgba *byte, rgbaStride int32) int32
	xWebPPictureImportRGBX         func(picture *WebPPicture, rgbx *byte, rgbxStride int32) int32
	xWebPPictureImportBGR          func(picture *WebPPicture, bgr *byte, bgrStride int32) int32
	xWebPPictureImportBGRA         func(picture *WebPPicture, bgra *byte, bgraStride int32) int32
	xWebPPictureImportBGRX         func(picture *WebPPicture, bgrx *byte, bgrxStride int32) int32
	xWebPPictureARGBToYUVA         func(picture *WebPPicture, colorspace int32) int32
	xWebPPictureARGBToYUVADithered func(picture *WebPPicture, colorspace int32, dithering float32) int32
	xWebPPictureSharpARGBToYUVA    func(picture *WebPPicture) int32
	xWebPPictureSmartARGBToYUVA    func(picture *WebPPicture) int32
	xWebPPictureYUVAToARGB         func(picture *WebPPicture) int32
	xWebPCleanupTransparentArea    func(picture *WebPPicture)
	xWebPPictureHasTransparency    func(picture *WebPPicture) int32
	xWebPBlendAlpha                func(picture *WebPPicture, backgroundRGB uint32)
	xWebPPlaneDistortion           func(src *byte, srcStride uintptr, ref *byte, refStride uintptr, width int32, height int32, xStep uintptr, distType int32, distortion *float32, result *float32) int32
	xWebPPictureDistortion         func(src *WebPPicture, ref *WebPPicture, metricType int32, result *float32) int32
	xWebPEncode                    func(config *WebPConfig, picture *WebPPicture) int32
	xWebPFree                      func(ptr uintptr)
	xWebPGetDecoderVersion         func() int32
	xWebPGetEncoderVersion         func() int32
)

func WebPGetInfo(data *byte, dataSize uintptr, width *int32, height *int32) int32 {
	return xWebPGetInfo(data, dataSize, width, height)
}
func WebPDecodeRGBA(data *byte, dataSize uintptr, width *int32, height *int32) *byte {
	return xWebPDecodeRGBA(data, dataSize, width, height)
}
func WebPDecodeARGB(data *byte, dataSize uintptr, width *int32, height *int32) *byte {
	return xWebPDecodeARGB(data, dataSize, width, height)
}
func WebPDecodeBGRA(data *byte, dataSize uintptr, width *int32, height *int32) *byte {
	return xWebPDecodeBGRA(data, dataSize, width, height)
}
func WebPDecodeRGB(data *byte, dataSize uintptr, width *int32, height *int32) *byte {
	return xWebPDecodeRGB(data, dataSize, width, height)
}
func WebPDecodeBGR(data *byte, dataSize uintptr, width *int32, height *int32) *byte {
	return xWebPDecodeBGR(data, dataSize, width, height)
}
func WebPDecodeRGBAInto(data *byte, dataSize uintptr, outputBuffer *byte, outputBufferSize uintptr, outputStride int32) *byte {
	return xWebPDecodeRGBAInto(data, dataSize, outputBuffer, outputBufferSize, outputStride)
}
func WebPDecodeARGBInto(data *byte, dataSize uintptr, outputBuffer *byte, outputBufferSize uintptr, outputStride int32) *byte {
	return xWebPDecodeARGBInto(data, dataSize, outputBuffer, outputBufferSize, outputStride)
}
func WebPDecodeBGRAInto(data *byte, dataSize uintptr, outputBuffer *byte, outputBufferSize uintptr, outputStride int32) *byte {
	return xWebPDecodeBGRAInto(data, dataSize, outputBuffer, outputBufferSize, outputStride)
}
func WebPDecodeRGBInto(data *byte, dataSize uintptr, outputBuffer *byte, outputBufferSize uintptr, outputStride int32) *byte {
	return xWebPDecodeRGBInto(data, dataSize, outputBuffer, outputBufferSize, outputStride)
}
func WebPDecodeBGRInto(data *byte, dataSize uintptr, outputBuffer *byte, outputBufferSize uintptr, outputStride int32) *byte {
	return xWebPDecodeBGRInto(data, dataSize, outputBuffer, outputBufferSize, outputStride)
}
func WebPDecodeYUV(data *byte, dataSize uintptr, width *int32, height *int32, u **byte, v **byte, stride *int32, uvStride *int32) *byte {
	return xWebPDecodeYUV(data, dataSize, width, height, u, v, stride, uvStride)
}
func WebPDecodeYUVInto(data *byte, dataSize uintptr, luma *byte, lumaSize uintptr, lumaStride int32, u *byte, uSize uintptr, uStride int32, v *byte, vSize uintptr, vStride int32) *byte {
	return xWebPDecodeYUVInto(data, dataSize, luma, lumaSize, lumaStride, u, uSize, uStride, v, vSize, vStride)
}
func WebPGetFeaturesInternal(data *byte, dataSize uintptr, features *WebPBitstreamFeatures, abiVersion int32) VP8StatusCode {
	return xWebPGetFeaturesInternal(data, dataSize, features, abiVersion)
}
func WebPInitDecBufferInternal(buffer *WebPDecBuffer, abiVersion int32) int32 {
	return xWebPInitDecBufferInternal(buffer, abiVersion)
}
func WebPFreeDecBuffer(buffer *WebPDecBuffer) {
	xWebPFreeDecBuffer(buffer)
}
func WebPInitDecoderConfigInternal(config *WebPDecoderConfig, abiVersion int32) int32 {
	return xWebPInitDecoderConfigInternal(config, abiVersion)
}
func WebPValidateDecoderConfig(config *WebPDecoderConfig) int32 {
	return xWebPValidateDecoderConfig(config)
}
func WebPDecode(data *byte, dataSize uintptr, config *WebPDecoderConfig) VP8StatusCode {
	return xWebPDecode(data, dataSize, config)
}
func WebPINewDecoder(outputBuffer *WebPDecBuffer) uintptr {
	return xWebPINewDecoder(outputBuffer)
}
func WebPINewRGB(csp int32, outputBuffer *byte, outputBufferSize uintptr, outputStride int32) uintptr {
	return xWebPINewRGB(csp, outputBuffer, outputBufferSize, outputStride)
}
func WebPINewYUVA(luma *byte, lumaSize uintptr, lumaStride int32, u *byte, uSize uintptr, uStride int32, v *byte, vSize uintptr, vStride int32, a *byte, aSize uintptr, aStride int32) uintptr {
	return xWebPINewYUVA(luma, lumaSize, lumaStride, u, uSize, uStride, v, vSize, vStride, a, aSize, aStride)
}
func WebPINewYUV(luma *byte, lumaSize uintptr, lumaStride int32, u *byte, uSize uintptr, uStride int32, v *byte, vSize uintptr, vStride int32) uintptr {
	return xWebPINewYUV(luma, lumaSize, lumaStride, u, uSize, uStride, v, vSize, vStride)
}
func WebPIDelete(idec uintptr) {
	xWebPIDelete(idec)
}
func WebPIAppend(idec uintptr, data *byte, dataSize uintptr) VP8StatusCode {
	return xWebPIAppend(idec, data, dataSize)
}
func WebPIUpdate(idec uintptr, data *byte, dataSize uintptr) VP8StatusCode {
	return xWebPIUpdate(idec, data, dataSize)
}
func WebPIDecGetRGB(idec uintptr, lastY *int32, width *int32, height *int32, stride *int32) *byte {
	return xWebPIDecGetRGB(idec, lastY, width, height, stride)
}
func WebPIDecGetYUVA(idec uintptr, lastY *int32, u **byte, v **byte, a **byte, width *int32, height *int32, stride *int32, uvStride *int32, aStride *int32) *byte {
	return xWebPIDecGetYUVA(idec, lastY, u, v, a, width, height, stride, uvStride, aStride)
}
func WebPIDecodedArea(idec uintptr, left *int32, top *int32, width *int32, height *int32) *WebPDecBuffer {
	return xWebPIDecodedArea(idec, left, top, width, height)
}
func WebPIDecode(data *byte, dataSize uintptr, config *WebPDecoderConfig) uintptr {
	return xWebPIDecode(data, dataSize, config)
}
func WebPEncodeRGBA(rgba *byte, width int32, height int32, stride int32, quality float32, output **byte) uintptr {
	return xWebPEncodeRGBA(rgba, width, height, stride, quality, output)
}
func WebPEncodeRGB(rgb *byte, width int32, height int32, stride int32, quality float32, output **byte) uintptr {
	return xWebPEncodeRGB(rgb, width, height, stride, quality, output)
}
func WebPEncodeBGR(bgr *byte, width int32, height int32, stride int32, quality float32, output **byte) uintptr {
	return xWebPEncodeBGR(bgr, width, height, stride, quality, output)
}
func WebPEncodeBGRA(bgra *byte, width int32, height int32, stride int32, quality float32, output **byte) uintptr {
	return xWebPEncodeBGRA(bgra, width, height, stride, quality, output)
}
func WebPEncodeLosslessRGBA(rgba *byte, width int32, height int32, stride int32, output **byte) uintptr {
	return xWebPEncodeLosslessRGBA(rgba, width, height, stride, output)
}
func WebPEncodeLosslessRGB(rgb *byte, width int32, height int32, stride int32, output **byte) uintptr {
	return xWebPEncodeLosslessRGB(rgb, width, height, stride, output)
}
func WebPEncodeLosslessBGR(bgr *byte, width int32, height int32, stride int32, output **byte) uintptr {
	return xWebPEncodeLosslessBGR(bgr, width, height, stride, output)
}
func WebPEncodeLosslessBGRA(bgra *byte, width int32, height int32, stride int32, output **byte) uintptr {
	return xWebPEncodeLosslessBGRA(bgra, width, height, stride, output)
}
func WebPConfigInitInternal(config *WebPConfig, preset int32, quality float32, abiVersion int32) int32 {
	return xWebPConfigInitInternal(config, preset, quality, abiVersion)
}
func WebPConfigLosslessPreset(config *WebPConfig, level int32) int32 {
	return xWebPConfigLosslessPreset(config, level)
}
func WebPValidateConfig(config *WebPConfig) int32 {
	return xWebPValidateConfig(config)
}
func WebPMemoryWriterInit(writer *WebPMemoryWriter) {
	xWebPMemoryWriterInit(writer)
}
func WebPMemoryWriterClear(writer *WebPMemoryWriter) {
	xWebPMemoryWriterClear(writer)
}
func WebPMemoryWrite(data *byte, dataSize uintptr, picture *WebPPicture) int32 {
	return xWebPMemoryWrite(data, dataSize, picture)
}
func WebPPictureInitInternal(picture *WebPPicture, abiVersion int32) int32 {
	return xWebPPictureInitInternal(picture, abiVersion)
}
func WebPPictureAlloc(picture *WebPPicture) int32 {
	return xWebPPictureAlloc(picture)
}
func WebPPictureFree(picture *WebPPicture) {
	xWebPPictureFree(picture)
}
func WebPPictureCopy(src *WebPPicture, dst *WebPPicture) int32 {
	return xWebPPictureCopy(src, dst)
}
func WebPPictureCrop(picture *WebPPicture, left int32, top int32, width int32, height int32) int32 {
	return xWebPPictureCrop(picture, left, top, width, height)
}
func WebPPictureView(src *WebPPicture, left int32, top int32, width int32, height int32, dst *WebPPicture) int32 {
	return xWebPPictureView(src, left, top, width, height, dst)
}
func WebPPictureIsView(picture *WebPPicture) int32 {
	return xWebPPictureIsView(picture)
}
func WebPPictureRescale(picture *WebPPicture, width int32, height int32) int32 {
	return xWebPPictureRescale(picture, width, height)
}
func WebPPictureImportRGB(picture *WebPPicture, rgb *byte, rgbStride int32) int32 {
	return xWebPPictureImportRGB(picture, rgb, rgbStride)
}
func WebPPictureImportRGBA(picture *WebPPicture, rgba *byte, rgbaStride int32) int32 {
	return xWebPPictureImportRGBA(picture, rgba, rgbaStride)
}
func WebPPictureImportRGBX(picture *WebPPicture, rgbx *byte, rgbxStride int32) int32 {
	return xWebPPictureImportRGBX(picture, rgbx, rgbxStride)
}
func WebPPictureImportBGR(picture *WebPPicture, bgr *byte, bgrStride int32) int32 {
	return xWebPPictureImportBGR(picture, bgr, bgrStride)
}
func WebPPictureImportBGRA(picture *WebPPicture, bgra *byte, bgraStride int32) int32 {
	return xWebPPictureImportBGRA(picture, bgra, bgraStride)
}
func WebPPictureImportBGRX(picture *WebPPicture, bgrx *byte, bgrxStride int32) int32 {
	return xWebPPictureImportBGRX(picture, bgrx, bgrxStride)
}
func WebPPictureARGBToYUVA(picture *WebPPicture, colorspace int32) int32 {
	return xWebPPictureARGBToYUVA(picture, colorspace)
}
func WebPPictureARGBToYUVADithered(picture *WebPPicture, colorspace int32, dithering float32) int32 {
	return xWebPPictureARGBToYUVADithered(picture, colorspace, dithering)
}
func WebPPictureSharpARGBToYUVA(picture *WebPPicture) int32 {
	return xWebPPictureSharpARGBToYUVA(picture)
}
func WebPPictureSmartARGBToYUVA(picture *WebPPicture) int32 {
	return xWebPPictureSmartARGBToYUVA(picture)
}
func WebPPictureYUVAToARGB(picture *WebPPicture) int32 {
	return xWebPPictureYUVAToARGB(picture)
}
func WebPCleanupTransparentArea(picture *WebPPicture) {
	xWebPCleanupTransparentArea(picture)
}
func WebPPictureHasTransparency(picture *WebPPicture) int32 {
	return xWebPPictureHasTransparency(picture)
}
func WebPBlendAlpha(picture *WebPPicture, backgroundRGB uint32) {
	xWebPBlendAlpha(picture, backgroundRGB)
}
func WebPPlaneDistortion(src *byte, srcStride uintptr, ref *byte, refStride uintptr, width int32, height int32, xStep uintptr, distType int32, distortion *float32, result *float32) int32 {
	return xWebPPlaneDistortion(src, srcStride, ref, refStride, width, height, xStep, distType, distortion, result)
}
func WebPPictureDistortion(src *WebPPicture, ref *WebPPicture, metricType int32, result *float32) int32 {
	return xWebPPictureDistortion(src, ref, metricType, result)
}
func WebPEncode(config *WebPConfig, picture *WebPPicture) int32 {
	return xWebPEncode(config, picture)
}
func WebPFree(ptr uintptr) {
	xWebPFree(ptr)
}
func WebPGetDecoderVersion() int32 {
	return xWebPGetDecoderVersion()
}
func WebPGetEncoderVersion() int32 {
	return xWebPGetEncoderVersion()
}
func registerAll(lib uintptr) error {
	if err := register(lib, &xWebPGetInfo, "WebPGetInfo"); err != nil {
		return err
	}
	if err := register(lib, &xWebPDecodeRGBA, "WebPDecodeRGBA"); err != nil {
		return err
	}
	if err := register(lib, &xWebPDecodeARGB, "WebPDecodeARGB"); err != nil {
		return err
	}
	if err := register(lib, &xWebPDecodeBGRA, "WebPDecodeBGRA"); err != nil {
		return err
	}
	if err := register(lib, &xWebPDecodeRGB, "WebPDecodeRGB"); err != nil {
		return err
	}
	if err := register(lib, &xWebPDecodeBGR, "WebPDecodeBGR"); err != nil {
		return err
	}
	if err := register(lib, &xWebPDecodeRGBAInto, "WebPDecodeRGBAInto"); err != nil {
		return err
	}
	if err := register(lib, &xWebPDecodeARGBInto, "WebPDecodeARGBInto"); err != nil {
		return err
	}
	if err := register(lib, &xWebPDecodeBGRAInto, "WebPDecodeBGRAInto"); err != nil {
		return err
	}
	if err := register(lib, &xWebPDecodeRGBInto, "WebPDecodeRGBInto"); err != nil {
		return err
	}
	if err := register(lib, &xWebPDecodeBGRInto, "WebPDecodeBGRInto"); err != nil {
		return err
	}
	if err := register(lib, &xWebPDecodeYUV, "WebPDecodeYUV"); err != nil {
		return err
	}
	if err := register(lib, &xWebPDecodeYUVInto, "WebPDecodeYUVInto"); err != nil {
		return err
	}
	if err := register(lib, &xWebPGetFeaturesInternal, "WebPGetFeaturesInternal"); err != nil {
		return err
	}
	if err := register(lib, &xWebPInitDecBufferInternal, "WebPInitDecBufferInternal"); err != nil {
		return err
	}
	if err := register(lib, &xWebPFreeDecBuffer, "WebPFreeDecBuffer"); err != nil {
		return err
	}
	if err := register(lib, &xWebPInitDecoderConfigInternal, "WebPInitDecoderConfigInternal"); err != nil {
		return err
	}
	registerOptional(lib, &xWebPValidateDecoderConfig, "WebPValidateDecoderConfig")
	if err := register(lib, &xWebPDecode, "WebPDecode"); err != nil {
		return err
	}
	if err := register(lib, &xWebPINewDecoder, "WebPINewDecoder"); err != nil {
		return err
	}
	if err := register(lib, &xWebPINewRGB, "WebPINewRGB"); err != nil {
		return err
	}
	if err := register(lib, &xWebPINewYUVA, "WebPINewYUVA"); err != nil {
		return err
	}
	if err := register(lib, &xWebPINewYUV, "WebPINewYUV"); err != nil {
		return err
	}
	if err := register(lib, &xWebPIDelete, "WebPIDelete"); err != nil {
		return err
	}
	if err := register(lib, &xWebPIAppend, "WebPIAppend"); err != nil {
		return err
	}
	if err := register(lib, &xWebPIUpdate, "WebPIUpdate"); err != nil {
		return err
	}
	if err := register(lib, &xWebPIDecGetRGB, "WebPIDecGetRGB"); err != nil {
		return err
	}
	if err := register(lib, &xWebPIDecGetYUVA, "WebPIDecGetYUVA"); err != nil {
		return err
	}
	if err := register(lib, &xWebPIDecodedArea, "WebPIDecodedArea"); err != nil {
		return err
	}
	if err := register(lib, &xWebPIDecode, "WebPIDecode"); err != nil {
		return err
	}
	if err := register(lib, &xWebPEncodeRGBA, "WebPEncodeRGBA"); err != nil {
		return err
	}
	if err := register(lib, &xWebPEncodeRGB, "WebPEncodeRGB"); err != nil {
		return err
	}
	if err := register(lib, &xWebPEncodeBGR, "WebPEncodeBGR"); err != nil {
		return err
	}
	if err := register(lib, &xWebPEncodeBGRA, "WebPEncodeBGRA"); err != nil {
		return err
	}
	if err := register(lib, &xWebPEncodeLosslessRGBA, "WebPEncodeLosslessRGBA"); err != nil {
		return err
	}
	if err := register(lib, &xWebPEncodeLosslessRGB, "WebPEncodeLosslessRGB"); err != nil {
		return err
	}
	if err := register(lib, &xWebPEncodeLosslessBGR, "WebPEncodeLosslessBGR"); err != nil {
		return err
	}
	if err := register(lib, &xWebPEncodeLosslessBGRA, "WebPEncodeLosslessBGRA"); err != nil {
		return err
	}
	if err := register(lib, &xWebPConfigInitInternal, "WebPConfigInitInternal"); err != nil {
		return err
	}
	if err := register(lib, &xWebPConfigLosslessPreset, "WebPConfigLosslessPreset"); err != nil {
		return err
	}
	if err := register(lib, &xWebPValidateConfig, "WebPValidateConfig"); err != nil {
		return err
	}
	if err := register(lib, &xWebPMemoryWriterInit, "WebPMemoryWriterInit"); err != nil {
		return err
	}
	if err := register(lib, &xWebPMemoryWriterClear, "WebPMemoryWriterClear"); err != nil {
		return err
	}
	if err := register(lib, &xWebPMemoryWrite, "WebPMemoryWrite"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureInitInternal, "WebPPictureInitInternal"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureAlloc, "WebPPictureAlloc"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureFree, "WebPPictureFree"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureCopy, "WebPPictureCopy"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureCrop, "WebPPictureCrop"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureView, "WebPPictureView"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureIsView, "WebPPictureIsView"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureRescale, "WebPPictureRescale"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureImportRGB, "WebPPictureImportRGB"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureImportRGBA, "WebPPictureImportRGBA"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureImportRGBX, "WebPPictureImportRGBX"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureImportBGR, "WebPPictureImportBGR"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureImportBGRA, "WebPPictureImportBGRA"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureImportBGRX, "WebPPictureImportBGRX"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureARGBToYUVA, "WebPPictureARGBToYUVA"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureARGBToYUVADithered, "WebPPictureARGBToYUVADithered"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureSharpARGBToYUVA, "WebPPictureSharpARGBToYUVA"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureSmartARGBToYUVA, "WebPPictureSmartARGBToYUVA"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureYUVAToARGB, "WebPPictureYUVAToARGB"); err != nil {
		return err
	}
	if err := register(lib, &xWebPCleanupTransparentArea, "WebPCleanupTransparentArea"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureHasTransparency, "WebPPictureHasTransparency"); err != nil {
		return err
	}
	if err := register(lib, &xWebPBlendAlpha, "WebPBlendAlpha"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPlaneDistortion, "WebPPlaneDistortion"); err != nil {
		return err
	}
	if err := register(lib, &xWebPPictureDistortion, "WebPPictureDistortion"); err != nil {
		return err
	}
	if err := register(lib, &xWebPEncode, "WebPEncode"); err != nil {
		return err
	}
	if err := register(lib, &xWebPFree, "WebPFree"); err != nil {
		return err
	}
	if err := register(lib, &xWebPGetDecoderVersion, "WebPGetDecoderVersion"); err != nil {
		return err
	}
	if err := register(lib, &xWebPGetEncoderVersion, "WebPGetEncoderVersion"); err != nil {
		return err
	}

	return nil
}
